/*
Copyright © 2019 AWS Controller authors

Licensed under the Apache License, Version 2.0 (the &#34;License&#34;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &#34;AS IS&#34; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"encoding/json"
	"fmt"
	"strings"

	metav1alpha1 "go.awsctrl.io/manager/apis/meta/v1alpha1"
	controllerutils "go.awsctrl.io/manager/controllers/utils"
	cfnencoder "go.awsctrl.io/manager/encoding/cloudformation"

	"github.com/awslabs/goformation/v4/cloudformation"
	"github.com/awslabs/goformation/v4/cloudformation/iam"
	"k8s.io/client-go/dynamic"
)

// GetNotificationARNs is an autogenerated deepcopy function, will return notifications for stack
func (in *Group) GetNotificationARNs() []string {
	notifcations := []string{}
	for _, notifarn := range in.Spec.NotificationARNs {
		notifcations = append(notifcations, *notifarn)
	}
	return notifcations
}

// GetTemplate will return the JSON version of the CFN to use.
func (in *Group) GetTemplate(client dynamic.Interface) (string, error) {
	if client == nil {
		return "", fmt.Errorf("k8s client not loaded for template")
	}
	template := cloudformation.NewTemplate()

	template.Description = "AWS Controller - iam.Group (ac-{TODO})"

	template.Outputs = map[string]interface{}{
		"ResourceRef": map[string]interface{}{
			"Value": cloudformation.Ref("Group"),
			"Export": map[string]interface{}{
				"Name": in.Name + "Ref",
			},
		},
		"Arn": map[string]interface{}{
			"Value":  cloudformation.GetAtt("Group", "Arn"),
			"Export": map[string]interface{}{"Name": in.Name + "Arn"},
		},
	}

	iamGroup := &iam.Group{}

	// TODO(christopherhein) move these to a defaulter
	if in.Spec.GroupName == "" {
		iamGroup.GroupName = in.Name
	}

	if in.Spec.GroupName != "" {
		iamGroup.GroupName = in.Spec.GroupName
	}

	if len(in.Spec.ManagedPolicyRefs) > 0 {
		iamGroupManagedPolicyRefs := []string{}

		for _, item := range in.Spec.ManagedPolicyRefs {
			iamGroupManagedPolicyRefsItem := item.DeepCopy()

			if iamGroupManagedPolicyRefsItem.ObjectRef.Namespace == "" {
				iamGroupManagedPolicyRefsItem.ObjectRef.Namespace = in.Namespace
			}

		}

		iamGroup.ManagedPolicyArns = iamGroupManagedPolicyRefs
	}

	if in.Spec.Path != "" {
		iamGroup.Path = in.Spec.Path
	}

	iamGroupPolicies := []iam.Group_Policy{}

	for _, item := range in.Spec.Policies {
		iamGroupPolicy := iam.Group_Policy{}

		if item.PolicyDocument != "" {
			iamGroupPolicyJSON := make(map[string]interface{})
			err := json.Unmarshal([]byte(item.PolicyDocument), &iamGroupPolicyJSON)
			if err != nil {
				return "", err
			}
			iamGroupPolicy.PolicyDocument = iamGroupPolicyJSON
		}

		if item.PolicyName != "" {
			iamGroupPolicy.PolicyName = item.PolicyName
		}

	}

	if len(iamGroupPolicies) > 0 {
		iamGroup.Policies = iamGroupPolicies
	}

	template.Resources = map[string]cloudformation.Resource{
		"Group": iamGroup,
	}

	// json, err := template.JSONWithOptions(&intrinsics.ProcessorOptions{NoEvaluateConditions: true})
	json, err := template.JSON()
	if err != nil {
		return "", err
	}

	return string(json), nil
}

// GetStackID will return stackID
func (in *Group) GetStackID() string {
	return in.Status.StackID
}

// GenerateStackName will generate a StackName
func (in *Group) GenerateStackName() string {
	return strings.Join([]string{"iam", "group", in.GetName(), in.GetNamespace()}, "-")
}

// GetStackName will return stackName
func (in *Group) GetStackName() string {
	return in.Spec.StackName
}

// GetTemplateVersionLabel will return the stack template version
func (in *Group) GetTemplateVersionLabel() (value string, ok bool) {
	value, ok = in.Labels[controllerutils.StackTemplateVersionLabel]
	return
}

// GetParameters will return CFN Parameters
func (in *Group) GetParameters() map[string]string {
	params := map[string]string{}
	cfnencoder.MarshalTypes(params, in.Spec, "Parameter")
	return params
}

// GetCloudFormationMeta will return CFN meta object
func (in *Group) GetCloudFormationMeta() metav1alpha1.CloudFormationMeta {
	return in.Spec.CloudFormationMeta
}

// GetStatus will return the CFN Status
func (in *Group) GetStatus() metav1alpha1.ConditionStatus {
	return in.Status.Status
}

// SetStackID will put a stackID
func (in *Group) SetStackID(input string) {
	in.Status.StackID = input
	return
}

// SetStackName will return stackName
func (in *Group) SetStackName(input string) {
	in.Spec.StackName = input
	return
}

// SetTemplateVersionLabel will set the template version label
func (in *Group) SetTemplateVersionLabel() {
	if len(in.Labels) == 0 {
		in.Labels = map[string]string{}
	}

	in.Labels[controllerutils.StackTemplateVersionLabel] = controllerutils.ComputeHash(in.Spec)
}

// TemplateVersionChanged will return bool if template has changed
func (in *Group) TemplateVersionChanged() bool {
	// Ignore bool since it will still record changed
	label, _ := in.GetTemplateVersionLabel()
	return label != controllerutils.ComputeHash(in.Spec)
}

// SetStatus will set status for object
func (in *Group) SetStatus(status *metav1alpha1.StatusMeta) {
	in.Status.StatusMeta = *status
}
