/*
Copyright © 2019 AWS Controller authors

Licensed under the Apache License, Version 2.0 (the &#34;License&#34;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &#34;AS IS&#34; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"encoding/json"
	"strings"

	metav1alpha1 "go.awsctrl.io/manager/apis/meta/v1alpha1"
	controllerutils "go.awsctrl.io/manager/controllers/utils"
	cfnencoder "go.awsctrl.io/manager/encoding/cloudformation"

	goformation "github.com/awslabs/goformation/v3/cloudformation"
	"github.com/awslabs/goformation/v3/cloudformation/ecr"
	"github.com/awslabs/goformation/v3/intrinsics"
)

// GetNotificationARNs is an autogenerated deepcopy function, will return notifications for stack
func (in *Repository) GetNotificationARNs() []string {
	notifcations := []string{}
	for _, notifarn := range in.Spec.NotificationARNs {
		notifcations = append(notifcations, *notifarn)
	}
	return notifcations
}

// GetTemplate will return the JSON version of the CFN to use.
func (in *Repository) GetTemplate() (string, error) {
	template := goformation.NewTemplate()

	template.Description = "AWS Controller - ecr.Repository (ac-{TODO})"

	// GenerateTemplateFunctions
	ecrRepository := &ecr.Repository{}

	if in.Spec.RepositoryName != "" {
		ecrRepository.RepositoryName = in.Spec.RepositoryName
	}

	if in.Spec.RepositoryPolicyText != "" {
		ecrRepositoryJSON := make(map[string]interface{})
		err := json.Unmarshal([]byte(in.Spec.RepositoryPolicyText), &ecrRepositoryJSON)
		if err != nil {
			return "", err
		}
		ecrRepository.RepositoryPolicyText = ecrRepositoryJSON
	}

	template.Resources = map[string]goformation.Resource{
		"Repository": ecrRepository,
	}

	json, err := template.JSONWithOptions(&intrinsics.ProcessorOptions{NoEvaluateConditions: true})
	if err != nil {
		return "", err
	}

	return string(json), nil
}

// GetStackID will return stackID
func (in *Repository) GetStackID() string {
	return in.Status.StackID
}

// GenerateStackName will generate a StackName
func (in *Repository) GenerateStackName() string {
	return strings.Join([]string{"ecr", "repository", in.GetName(), in.GetNamespace()}, "-")
}

// GetStackName will return stackName
func (in *Repository) GetStackName() string {
	return in.Spec.StackName
}

// GetTemplateVersionLabel will return the stack template version
func (in *Repository) GetTemplateVersionLabel() (value string, ok bool) {
	value, ok = in.Labels[controllerutils.StackTemplateVersionLabel]
	return
}

// GetParameters will return CFN Parameters
func (in *Repository) GetParameters() map[string]string {
	params := map[string]string{}
	cfnencoder.MarshalTypes(params, in.Spec, "Parameter")
	return params
}

// GetCloudFormationMeta will return CFN meta object
func (in *Repository) GetCloudFormationMeta() metav1alpha1.CloudFormationMeta {
	return in.Spec.CloudFormationMeta
}

// GetStatus will return the CFN Status
func (in *Repository) GetStatus() metav1alpha1.ConditionStatus {
	return in.Status.Status
}

// SetStackID will put a stackID
func (in *Repository) SetStackID(input string) {
	in.Status.StackID = input
	return
}

// SetStackName will return stackName
func (in *Repository) SetStackName(input string) {
	in.Spec.StackName = input
	return
}

// SetTemplateVersionLabel will set the template version label
func (in *Repository) SetTemplateVersionLabel() {
	if len(in.Labels) == 0 {
		in.Labels = map[string]string{}
	}

	in.Labels[controllerutils.StackTemplateVersionLabel] = controllerutils.ComputeHash(in.Spec)
}

// TemplateVersionChanged will return bool if template has changed
func (in *Repository) TemplateVersionChanged() bool {
	// Ignore bool since it will still record changed
	label, _ := in.GetTemplateVersionLabel()
	return label != controllerutils.ComputeHash(in.Spec)
}

// SetStatus will set status for object
func (in *Repository) SetStatus(status *metav1alpha1.StatusMeta) {
	in.Status.StatusMeta = *status
}
