// +build !ignore_autogenerated

// Code generated by main. DO NOT EDIT.

package v1alpha1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudFormationMeta) DeepCopyInto(out *CloudFormationMeta) {
	*out = *in
	if in.NotificationARNs != nil {
		in, out := &in.NotificationARNs, &out.NotificationARNs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudFormationMeta.
func (in *CloudFormationMeta) DeepCopy() *CloudFormationMeta {
	if in == nil {
		return nil
	}
	out := new(CloudFormationMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusMeta) DeepCopyInto(out *StatusMeta) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusMeta.
func (in *StatusMeta) DeepCopy() *StatusMeta {
	if in == nil {
		return nil
	}
	out := new(StatusMeta)
	in.DeepCopyInto(out)
	return out
}
