/*
Copyright © 2019 AWS Controller authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package stackobject will generate the apis/<service>/zz_<resource>.stackobject.go
package stackobject

import (
	"fmt"
	"path/filepath"
	"strings"

	"awsctrl.io/generator/pkg/input"
	"awsctrl.io/generator/pkg/resource"
)

var _ input.File = &StackObject{}

// StackObject scaffolds the apis/<groups>/<version>/zz_generated.<resource>.stackobject.go
type StackObject struct {
	input.Input

	// Resource is a resource in the API group
	Resource *resource.Resource
}

// GetInput implements input.File
func (in *StackObject) GetInput() input.Input {
	if in.Path == "" {
		in.Path = strings.ToLower(filepath.Join("apis", in.Resource.Group, in.Resource.Version, fmt.Sprintf("zz_generated.%s.stackobject.go", in.Resource.Kind)))
	}
	in.TemplateBody = stackobjectTemplate
	return in.Input
}

// Validate validates the values
func (g *StackObject) Validate() error {
	return g.Resource.Validate()
}

const stackobjectTemplate = `{{ .Boilerplate }}

package {{ .Resource.Version }}

import (
	"strings"
	"reflect"

	metav1alpha1 "awsctrl.io/apis/meta/v1alpha1"
	controllerutils "awsctrl.io/controllers/utils"
	cfnencoder "awsctrl.io/encoding/cloudformation"

	cfnhelpers "awsctrl.io/aws/cloudformation"
	goformation "github.com/awslabs/goformation/v3/cloudformation"
	"github.com/awslabs/goformation/v3/cloudformation/{{ .Resource.Group  }}"
	"github.com/awslabs/goformation/v3/intrinsics"
)

// GetNotificationARNs is an autogenerated deepcopy function, will return notifications for stack
func (in *{{ .Resource.Kind }}) GetNotificationARNs() []string {
	notifcations := []string{}
	for _, notifarn := range in.Spec.NotificationARNs {
		notifcations = append(notifcations, *notifarn)
	}
	return notifcations
}

// GetTemplate will return the JSON version of the CFN to use.
func (in *{{ .Resource.Kind }}) GetTemplate() (string, error) {
	template := goformation.NewTemplate()

	template.Description = "AWS Controller - {{ .Resource.Group  }}.{{ .Resource.Kind }} (ac-{TODO})"

	{{ range $name, $property := .Resource.ResourceType.GetProperties }}
	{{- if $property.IsParameter }}
	if in.Spec.{{ $name }} != "" {
		template.Parameters["{{ $name }}"] = cfnhelpers.Parameter{
			Type:        "{{ $property.GetType | title }}",
			Description: "{{ $property.GetDocumentation }}",
			Default:     "{{ $property.GetDefault }}",
		}
	}
	{{ end }}
	{{ end }}

	{{ range $resourcename, $resource := .Resource.PropertyTypes }}
	{{ range $name, $property := $resource.GetProperties }}
	{{- if $property.IsParameter }}
	if in.Spec.{{ $resourcename }}.{{ $name }} != "" {
		template.Parameters["{{ $name }}"] = cfnhelpers.Parameter{
			Type:        "{{ $property.GetType | title }}",
			Description: "{{ $property.GetDocumentation }}",
			Default:     "{{ $property.GetDefault }}",
		}
	}
	{{ end }}
	{{ end }}
	{{ end }}

	{{ .Resource.Group | lower }}{{ .Resource.Kind }} := &{{ .Resource.Group | lower }}.{{ .Resource.Kind }}{}

	{{- range $name, $property := .Resource.ResourceType.GetProperties }}
	{{- if $property.IsParameter }}
	if in.Spec.{{ $name }} != "" {
		{{ $.Resource.Group | lower }}{{ $.Resource.Kind }}.{{ $name }} = goformation.Ref("{{ $name }}")
	}
	{{ end }}
	{{ end }}

	{{- range $resourcename, $resource := .Resource.PropertyTypes }}
	{{ $.Resource.Group | lower }}{{ $.Resource.Kind }}{{ $resourcename }} := &{{ $.Resource.Group | lower }}.{{ $.Resource.Kind }}_{{ $resourcename }}{}
	{{- range $name, $property := $resource.GetProperties }}
	{{- if $property.IsParameter }}
	if in.Spec.{{ $resourcename }}.{{ $name }} != "" {
		{{ $.Resource.Group | lower }}{{ $.Resource.Kind }}{{ $resourcename }}.{{ $name }} = goformation.Ref("{{ $name }}")
	}
	{{ end }}
	{{ end }}
	if !reflect.DeepEqual(&{{ $.Resource.Group | lower }}.{{ $.Resource.Kind }}_{{ $resourcename }}{}, {{ $.Resource.Group | lower }}{{ $.Resource.Kind }}{{ $resourcename }}) {
		{{ $.Resource.Group | lower }}{{ $.Resource.Kind }}.{{ $resourcename }} = {{ $.Resource.Group | lower }}{{ $.Resource.Kind }}{{ $resourcename }}
	}
	{{ end }}

	template.Resources["{{ .Resource.Kind }}"] = {{ .Resource.Group | lower }}{{ .Resource.Kind }}


	{{ if false }}
	// template.Outputs["Ref"] = cfnhelpers.Output{
	// 	Value: cloudformation.Ref("{{ .Resource.Kind }}"),
	// 	Export: map[string]string{
	// 		"Name": "{{ .Resource.Kind }}Ref",
	// 	},
	// }
	{{ end }}

	json, err := template.JSONWithOptions(&intrinsics.ProcessorOptions{NoEvaluateConditions: true})
	if err != nil {
		return "", err
	}

	return string(json), nil
}

// GetStackID will return stackID
func (in *{{ .Resource.Kind }}) GetStackID() string {
	return in.Status.StackID
}

// GenerateStackName will generate a StackName
func (in *{{ .Resource.Kind }}) GenerateStackName() string {
	return strings.Join([]string{"{{ .Resource.Group | lower }}", "{{ .Resource.Kind | lower }}", in.GetName(), in.GetNamespace()}, "-")
}

// GetStackName will return stackName
func (in *{{ .Resource.Kind }}) GetStackName() string {
	return in.Spec.StackName
}

func (in *{{ .Resource.Kind }}) GetTemplateVersionLabel() (value string, ok bool) {
	value, ok = in.Labels[controllerutils.StackTemplateVersionLabel]
	return
}

// GetParameters will return CFN Parameters
func (in *{{ .Resource.Kind }}) GetParameters() map[string]string {
	params := map[string]string{}
	cfnencoder.MarshalTypes(params, in.Spec, "Parameter")
	return params
}

// GetCloudFormationMeta will return CFN meta object
func (in *{{ .Resource.Kind }}) GetCloudFormationMeta() metav1alpha1.CloudFormationMeta {
	return in.Spec.CloudFormationMeta
}

// GetStatus will return the CFN Status
func (in *{{ .Resource.Kind }}) GetStatus() metav1alpha1.ConditionStatus {
	return in.Status.Status
}

// SetStackID will put a stackID
func (in *{{ .Resource.Kind }}) SetStackID(input string) {
	in.Status.StackID = input
	return
}

// SetStackName will return stackName
func (in *{{ .Resource.Kind }}) SetStackName(input string) {
	in.Spec.StackName = input
	return
}

// SetTemplateVersionLabel will set the template version label
func (in *{{ .Resource.Kind }}) SetTemplateVersionLabel() {
	if len(in.Labels) == 0 {
		in.Labels = map[string]string{}
	}

	in.Labels[controllerutils.StackTemplateVersionLabel] = controllerutils.ComputeHash(in.Spec)
}

// TemplateVersionChanged will return bool if template has changed
func (in *{{ .Resource.Kind }}) TemplateVersionChanged() bool {
	// Ignore bool since it will still record changed
	label, _ := in.GetTemplateVersionLabel()
	return label != controllerutils.ComputeHash(in.Spec)
}

// SetStatus will set status for object
func (in *{{ .Resource.Kind }}) SetStatus(status *metav1alpha1.StatusMeta) {
	in.Status.StatusMeta = *status
}
`
