// +build !ignore_autogenerated

/*
Copyright © 2019 AWS Controller authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheck) DeepCopyInto(out *HealthCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheck.
func (in *HealthCheck) DeepCopy() *HealthCheck {
	if in == nil {
		return nil
	}
	out := new(HealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckList) DeepCopyInto(out *HealthCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HealthCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckList.
func (in *HealthCheckList) DeepCopy() *HealthCheckList {
	if in == nil {
		return nil
	}
	out := new(HealthCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckOutput) DeepCopyInto(out *HealthCheckOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckOutput.
func (in *HealthCheckOutput) DeepCopy() *HealthCheckOutput {
	if in == nil {
		return nil
	}
	out := new(HealthCheckOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckSpec) DeepCopyInto(out *HealthCheckSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	in.HealthCheckConfig.DeepCopyInto(&out.HealthCheckConfig)
	if in.HealthCheckTags != nil {
		in, out := &in.HealthCheckTags, &out.HealthCheckTags
		*out = make([]HealthCheck_HealthCheckTag, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckSpec.
func (in *HealthCheckSpec) DeepCopy() *HealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(HealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckStatus) DeepCopyInto(out *HealthCheckStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckStatus.
func (in *HealthCheckStatus) DeepCopy() *HealthCheckStatus {
	if in == nil {
		return nil
	}
	out := new(HealthCheckStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheck_AlarmIdentifier) DeepCopyInto(out *HealthCheck_AlarmIdentifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheck_AlarmIdentifier.
func (in *HealthCheck_AlarmIdentifier) DeepCopy() *HealthCheck_AlarmIdentifier {
	if in == nil {
		return nil
	}
	out := new(HealthCheck_AlarmIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheck_HealthCheckConfig) DeepCopyInto(out *HealthCheck_HealthCheckConfig) {
	*out = *in
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.AlarmIdentifier = in.AlarmIdentifier
	if in.ChildHealthChecks != nil {
		in, out := &in.ChildHealthChecks, &out.ChildHealthChecks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheck_HealthCheckConfig.
func (in *HealthCheck_HealthCheckConfig) DeepCopy() *HealthCheck_HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheck_HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheck_HealthCheckTag) DeepCopyInto(out *HealthCheck_HealthCheckTag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheck_HealthCheckTag.
func (in *HealthCheck_HealthCheckTag) DeepCopy() *HealthCheck_HealthCheckTag {
	if in == nil {
		return nil
	}
	out := new(HealthCheck_HealthCheckTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedZone) DeepCopyInto(out *HostedZone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedZone.
func (in *HostedZone) DeepCopy() *HostedZone {
	if in == nil {
		return nil
	}
	out := new(HostedZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedZoneList) DeepCopyInto(out *HostedZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostedZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedZoneList.
func (in *HostedZoneList) DeepCopy() *HostedZoneList {
	if in == nil {
		return nil
	}
	out := new(HostedZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedZoneOutput) DeepCopyInto(out *HostedZoneOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedZoneOutput.
func (in *HostedZoneOutput) DeepCopy() *HostedZoneOutput {
	if in == nil {
		return nil
	}
	out := new(HostedZoneOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedZoneSpec) DeepCopyInto(out *HostedZoneSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	out.QueryLoggingConfig = in.QueryLoggingConfig
	if in.VPCs != nil {
		in, out := &in.VPCs, &out.VPCs
		*out = make([]HostedZone_VPC, len(*in))
		copy(*out, *in)
	}
	out.HostedZoneConfig = in.HostedZoneConfig
	if in.HostedZoneTags != nil {
		in, out := &in.HostedZoneTags, &out.HostedZoneTags
		*out = make([]HostedZone_HostedZoneTag, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedZoneSpec.
func (in *HostedZoneSpec) DeepCopy() *HostedZoneSpec {
	if in == nil {
		return nil
	}
	out := new(HostedZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedZoneStatus) DeepCopyInto(out *HostedZoneStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedZoneStatus.
func (in *HostedZoneStatus) DeepCopy() *HostedZoneStatus {
	if in == nil {
		return nil
	}
	out := new(HostedZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedZone_HostedZoneConfig) DeepCopyInto(out *HostedZone_HostedZoneConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedZone_HostedZoneConfig.
func (in *HostedZone_HostedZoneConfig) DeepCopy() *HostedZone_HostedZoneConfig {
	if in == nil {
		return nil
	}
	out := new(HostedZone_HostedZoneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedZone_HostedZoneTag) DeepCopyInto(out *HostedZone_HostedZoneTag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedZone_HostedZoneTag.
func (in *HostedZone_HostedZoneTag) DeepCopy() *HostedZone_HostedZoneTag {
	if in == nil {
		return nil
	}
	out := new(HostedZone_HostedZoneTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedZone_QueryLoggingConfig) DeepCopyInto(out *HostedZone_QueryLoggingConfig) {
	*out = *in
	out.CloudWatchLogsLogGroup = in.CloudWatchLogsLogGroup
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedZone_QueryLoggingConfig.
func (in *HostedZone_QueryLoggingConfig) DeepCopy() *HostedZone_QueryLoggingConfig {
	if in == nil {
		return nil
	}
	out := new(HostedZone_QueryLoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedZone_VPC) DeepCopyInto(out *HostedZone_VPC) {
	*out = *in
	out.VPC = in.VPC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedZone_VPC.
func (in *HostedZone_VPC) DeepCopy() *HostedZone_VPC {
	if in == nil {
		return nil
	}
	out := new(HostedZone_VPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSet) DeepCopyInto(out *RecordSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSet.
func (in *RecordSet) DeepCopy() *RecordSet {
	if in == nil {
		return nil
	}
	out := new(RecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecordSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetGroup) DeepCopyInto(out *RecordSetGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetGroup.
func (in *RecordSetGroup) DeepCopy() *RecordSetGroup {
	if in == nil {
		return nil
	}
	out := new(RecordSetGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecordSetGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetGroupList) DeepCopyInto(out *RecordSetGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecordSetGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetGroupList.
func (in *RecordSetGroupList) DeepCopy() *RecordSetGroupList {
	if in == nil {
		return nil
	}
	out := new(RecordSetGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecordSetGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetGroupOutput) DeepCopyInto(out *RecordSetGroupOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetGroupOutput.
func (in *RecordSetGroupOutput) DeepCopy() *RecordSetGroupOutput {
	if in == nil {
		return nil
	}
	out := new(RecordSetGroupOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetGroupSpec) DeepCopyInto(out *RecordSetGroupSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	if in.RecordSets != nil {
		in, out := &in.RecordSets, &out.RecordSets
		*out = make([]RecordSetGroup_RecordSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.HostedZone = in.HostedZone
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetGroupSpec.
func (in *RecordSetGroupSpec) DeepCopy() *RecordSetGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RecordSetGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetGroupStatus) DeepCopyInto(out *RecordSetGroupStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetGroupStatus.
func (in *RecordSetGroupStatus) DeepCopy() *RecordSetGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RecordSetGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetGroup_AliasTarget) DeepCopyInto(out *RecordSetGroup_AliasTarget) {
	*out = *in
	out.HostedZone = in.HostedZone
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetGroup_AliasTarget.
func (in *RecordSetGroup_AliasTarget) DeepCopy() *RecordSetGroup_AliasTarget {
	if in == nil {
		return nil
	}
	out := new(RecordSetGroup_AliasTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetGroup_GeoLocation) DeepCopyInto(out *RecordSetGroup_GeoLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetGroup_GeoLocation.
func (in *RecordSetGroup_GeoLocation) DeepCopy() *RecordSetGroup_GeoLocation {
	if in == nil {
		return nil
	}
	out := new(RecordSetGroup_GeoLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetGroup_RecordSet) DeepCopyInto(out *RecordSetGroup_RecordSet) {
	*out = *in
	out.GeoLocation = in.GeoLocation
	out.HealthCheck = in.HealthCheck
	out.HostedZone = in.HostedZone
	if in.ResourceRecords != nil {
		in, out := &in.ResourceRecords, &out.ResourceRecords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.AliasTarget = in.AliasTarget
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetGroup_RecordSet.
func (in *RecordSetGroup_RecordSet) DeepCopy() *RecordSetGroup_RecordSet {
	if in == nil {
		return nil
	}
	out := new(RecordSetGroup_RecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetList) DeepCopyInto(out *RecordSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RecordSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetList.
func (in *RecordSetList) DeepCopy() *RecordSetList {
	if in == nil {
		return nil
	}
	out := new(RecordSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecordSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetOutput) DeepCopyInto(out *RecordSetOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetOutput.
func (in *RecordSetOutput) DeepCopy() *RecordSetOutput {
	if in == nil {
		return nil
	}
	out := new(RecordSetOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetSpec) DeepCopyInto(out *RecordSetSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	out.AliasTarget = in.AliasTarget
	out.HostedZone = in.HostedZone
	out.HealthCheck = in.HealthCheck
	if in.ResourceRecords != nil {
		in, out := &in.ResourceRecords, &out.ResourceRecords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.GeoLocation = in.GeoLocation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetSpec.
func (in *RecordSetSpec) DeepCopy() *RecordSetSpec {
	if in == nil {
		return nil
	}
	out := new(RecordSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetStatus) DeepCopyInto(out *RecordSetStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetStatus.
func (in *RecordSetStatus) DeepCopy() *RecordSetStatus {
	if in == nil {
		return nil
	}
	out := new(RecordSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSet_AliasTarget) DeepCopyInto(out *RecordSet_AliasTarget) {
	*out = *in
	out.HostedZone = in.HostedZone
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSet_AliasTarget.
func (in *RecordSet_AliasTarget) DeepCopy() *RecordSet_AliasTarget {
	if in == nil {
		return nil
	}
	out := new(RecordSet_AliasTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSet_GeoLocation) DeepCopyInto(out *RecordSet_GeoLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSet_GeoLocation.
func (in *RecordSet_GeoLocation) DeepCopy() *RecordSet_GeoLocation {
	if in == nil {
		return nil
	}
	out := new(RecordSet_GeoLocation)
	in.DeepCopyInto(out)
	return out
}
