/*
Copyright © 2019 AWS Controller authors

Licensed under the Apache License, Version 2.0 (the &#34;License&#34;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &#34;AS IS&#34; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"fmt"
	"reflect"
	"strings"

	metav1alpha1 "go.awsctrl.io/manager/apis/meta/v1alpha1"
	controllerutils "go.awsctrl.io/manager/controllers/utils"
	cfnencoder "go.awsctrl.io/manager/encoding/cloudformation"

	"github.com/awslabs/goformation/v4/cloudformation"
	"github.com/awslabs/goformation/v4/cloudformation/route53"
	"k8s.io/client-go/dynamic"
)

// GetNotificationARNs is an autogenerated deepcopy function, will return notifications for stack
func (in *RecordSet) GetNotificationARNs() []string {
	notifcations := []string{}
	for _, notifarn := range in.Spec.NotificationARNs {
		notifcations = append(notifcations, *notifarn)
	}
	return notifcations
}

// GetTemplate will return the JSON version of the CFN to use.
func (in *RecordSet) GetTemplate(client dynamic.Interface) (string, error) {
	if client == nil {
		return "", fmt.Errorf("k8s client not loaded for template")
	}
	template := cloudformation.NewTemplate()

	template.Description = "AWS Controller - route53.RecordSet (ac-{TODO})"

	template.Outputs = map[string]interface{}{
		"ResourceRef": map[string]interface{}{
			"Value": cloudformation.Ref("RecordSet"),
		},
	}

	route53RecordSet := &route53.RecordSet{}

	if in.Spec.HostedZoneName != "" {
		route53RecordSet.HostedZoneName = in.Spec.HostedZoneName
	}

	if in.Spec.Weight != route53RecordSet.Weight {
		route53RecordSet.Weight = in.Spec.Weight
	}

	// TODO(christopherhein) move these to a defaulter
	route53RecordSetHealthCheckItem := in.Spec.HealthCheck.DeepCopy()

	if route53RecordSetHealthCheckItem.ObjectRef.Namespace == "" {
		route53RecordSetHealthCheckItem.ObjectRef.Namespace = in.Namespace
	}

	in.Spec.HealthCheck = *route53RecordSetHealthCheckItem
	healthCheckId, err := in.Spec.HealthCheck.String(client)
	if err != nil {
		return "", err
	}

	if healthCheckId != "" {
		route53RecordSet.HealthCheckId = healthCheckId
	}

	if in.Spec.Region != "" {
		route53RecordSet.Region = in.Spec.Region
	}

	if in.Spec.SetIdentifier != "" {
		route53RecordSet.SetIdentifier = in.Spec.SetIdentifier
	}

	if in.Spec.Comment != "" {
		route53RecordSet.Comment = in.Spec.Comment
	}

	if in.Spec.Failover != "" {
		route53RecordSet.Failover = in.Spec.Failover
	}

	if in.Spec.MultiValueAnswer || !in.Spec.MultiValueAnswer {
		route53RecordSet.MultiValueAnswer = in.Spec.MultiValueAnswer
	}

	if !reflect.DeepEqual(in.Spec.AliasTarget, RecordSet_AliasTarget{}) {
		route53RecordSetAliasTarget := route53.RecordSet_AliasTarget{}

		if in.Spec.AliasTarget.DNSName != "" {
			route53RecordSetAliasTarget.DNSName = in.Spec.AliasTarget.DNSName
		}

		if in.Spec.AliasTarget.EvaluateTargetHealth || !in.Spec.AliasTarget.EvaluateTargetHealth {
			route53RecordSetAliasTarget.EvaluateTargetHealth = in.Spec.AliasTarget.EvaluateTargetHealth
		}

		// TODO(christopherhein) move these to a defaulter
		route53RecordSetAliasTargetHostedZoneItem := in.Spec.AliasTarget.HostedZone.DeepCopy()

		if route53RecordSetAliasTargetHostedZoneItem.ObjectRef.Namespace == "" {
			route53RecordSetAliasTargetHostedZoneItem.ObjectRef.Namespace = in.Namespace
		}

		in.Spec.AliasTarget.HostedZone = *route53RecordSetAliasTargetHostedZoneItem
		hostedZoneId, err := in.Spec.AliasTarget.HostedZone.String(client)
		if err != nil {
			return "", err
		}

		if hostedZoneId != "" {
			route53RecordSetAliasTarget.HostedZoneId = hostedZoneId
		}

		route53RecordSet.AliasTarget = &route53RecordSetAliasTarget
	}

	if in.Spec.Name != "" {
		route53RecordSet.Name = in.Spec.Name
	}

	if len(in.Spec.ResourceRecords) > 0 {
		route53RecordSet.ResourceRecords = in.Spec.ResourceRecords
	}

	if in.Spec.TTL != "" {
		route53RecordSet.TTL = in.Spec.TTL
	}

	if !reflect.DeepEqual(in.Spec.GeoLocation, RecordSet_GeoLocation{}) {
		route53RecordSetGeoLocation := route53.RecordSet_GeoLocation{}

		if in.Spec.GeoLocation.CountryCode != "" {
			route53RecordSetGeoLocation.CountryCode = in.Spec.GeoLocation.CountryCode
		}

		if in.Spec.GeoLocation.SubdivisionCode != "" {
			route53RecordSetGeoLocation.SubdivisionCode = in.Spec.GeoLocation.SubdivisionCode
		}

		if in.Spec.GeoLocation.ContinentCode != "" {
			route53RecordSetGeoLocation.ContinentCode = in.Spec.GeoLocation.ContinentCode
		}

		route53RecordSet.GeoLocation = &route53RecordSetGeoLocation
	}

	if in.Spec.Type != "" {
		route53RecordSet.Type = in.Spec.Type
	}

	// TODO(christopherhein) move these to a defaulter
	route53RecordSetHostedZoneItem := in.Spec.HostedZone.DeepCopy()

	if route53RecordSetHostedZoneItem.ObjectRef.Namespace == "" {
		route53RecordSetHostedZoneItem.ObjectRef.Namespace = in.Namespace
	}

	in.Spec.HostedZone = *route53RecordSetHostedZoneItem
	hostedZoneId, err := in.Spec.HostedZone.String(client)
	if err != nil {
		return "", err
	}

	if hostedZoneId != "" {
		route53RecordSet.HostedZoneId = hostedZoneId
	}

	template.Resources = map[string]cloudformation.Resource{
		"RecordSet": route53RecordSet,
	}

	// json, err := template.JSONWithOptions(&intrinsics.ProcessorOptions{NoEvaluateConditions: true})
	json, err := template.JSON()
	if err != nil {
		return "", err
	}

	return string(json), nil
}

// GetStackID will return stackID
func (in *RecordSet) GetStackID() string {
	return in.Status.StackID
}

// GenerateStackName will generate a StackName
func (in *RecordSet) GenerateStackName() string {
	return strings.Join([]string{"route53", "recordset", in.GetName(), in.GetNamespace()}, "-")
}

// GetStackName will return stackName
func (in *RecordSet) GetStackName() string {
	return in.Spec.StackName
}

// GetTemplateVersionLabel will return the stack template version
func (in *RecordSet) GetTemplateVersionLabel() (value string, ok bool) {
	value, ok = in.Labels[controllerutils.StackTemplateVersionLabel]
	return
}

// GetParameters will return CFN Parameters
func (in *RecordSet) GetParameters() map[string]string {
	params := map[string]string{}
	cfnencoder.MarshalTypes(params, in.Spec, "Parameter")
	return params
}

// GetCloudFormationMeta will return CFN meta object
func (in *RecordSet) GetCloudFormationMeta() metav1alpha1.CloudFormationMeta {
	return in.Spec.CloudFormationMeta
}

// GetStatus will return the CFN Status
func (in *RecordSet) GetStatus() metav1alpha1.ConditionStatus {
	return in.Status.Status
}

// SetStackID will put a stackID
func (in *RecordSet) SetStackID(input string) {
	in.Status.StackID = input
	return
}

// SetStackName will return stackName
func (in *RecordSet) SetStackName(input string) {
	in.Spec.StackName = input
	return
}

// SetTemplateVersionLabel will set the template version label
func (in *RecordSet) SetTemplateVersionLabel() {
	if len(in.Labels) == 0 {
		in.Labels = map[string]string{}
	}

	in.Labels[controllerutils.StackTemplateVersionLabel] = controllerutils.ComputeHash(in.Spec)
}

// TemplateVersionChanged will return bool if template has changed
func (in *RecordSet) TemplateVersionChanged() bool {
	// Ignore bool since it will still record changed
	label, _ := in.GetTemplateVersionLabel()
	return label != controllerutils.ComputeHash(in.Spec)
}

// SetStatus will set status for object
func (in *RecordSet) SetStatus(status *metav1alpha1.StatusMeta) {
	in.Status.StatusMeta = *status
}
