/*
Copyright © 2019 AWS Controller authors

Licensed under the Apache License, Version 2.0 (the &#34;License&#34;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an &#34;AS IS&#34; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"fmt"
	"reflect"
	"strings"

	metav1alpha1 "go.awsctrl.io/manager/apis/meta/v1alpha1"
	controllerutils "go.awsctrl.io/manager/controllers/utils"
	cfnencoder "go.awsctrl.io/manager/encoding/cloudformation"

	"github.com/awslabs/goformation/v4/cloudformation"
	"github.com/awslabs/goformation/v4/cloudformation/apigateway"
	"k8s.io/client-go/dynamic"
)

// GetNotificationARNs is an autogenerated deepcopy function, will return notifications for stack
func (in *Method) GetNotificationARNs() []string {
	notifcations := []string{}
	for _, notifarn := range in.Spec.NotificationARNs {
		notifcations = append(notifcations, *notifarn)
	}
	return notifcations
}

// GetTemplate will return the JSON version of the CFN to use.
func (in *Method) GetTemplate(client dynamic.Interface) (string, error) {
	if client == nil {
		return "", fmt.Errorf("k8s client not loaded for template")
	}
	template := cloudformation.NewTemplate()

	template.Description = "AWS Controller - apigateway.Method (ac-{TODO})"

	template.Outputs = map[string]interface{}{
		"ResourceRef": map[string]interface{}{
			"Value": cloudformation.Ref("Method"),
		},
	}

	apigatewayMethod := &apigateway.Method{}

	if in.Spec.OperationName != "" {
		apigatewayMethod.OperationName = in.Spec.OperationName
	}

	if !reflect.DeepEqual(in.Spec.RequestModels, map[string]string{}) {
		apigatewayMethod.RequestModels = in.Spec.RequestModels
	}

	// TODO(christopherhein) move these to a defaulter
	apigatewayMethodRequestValidatorItem := in.Spec.RequestValidator.DeepCopy()

	if apigatewayMethodRequestValidatorItem.ObjectRef.Kind == "" {
		apigatewayMethodRequestValidatorItem.ObjectRef.Kind = "Deployment"
	}

	if apigatewayMethodRequestValidatorItem.ObjectRef.APIVersion == "" {
		apigatewayMethodRequestValidatorItem.ObjectRef.APIVersion = "apigateway.awsctrl.io/v1alpha1"
	}

	if apigatewayMethodRequestValidatorItem.ObjectRef.Namespace == "" {
		apigatewayMethodRequestValidatorItem.ObjectRef.Namespace = in.Namespace
	}

	in.Spec.RequestValidator = *apigatewayMethodRequestValidatorItem
	requestValidatorId, err := in.Spec.RequestValidator.String(client)
	if err != nil {
		return "", err
	}

	if requestValidatorId != "" {
		apigatewayMethod.RequestValidatorId = requestValidatorId
	}

	if len(in.Spec.AuthorizationScopes) > 0 {
		apigatewayMethod.AuthorizationScopes = in.Spec.AuthorizationScopes
	}

	if in.Spec.AuthorizationType != "" {
		apigatewayMethod.AuthorizationType = in.Spec.AuthorizationType
	}

	if !reflect.DeepEqual(in.Spec.Integration, Method_Integration{}) {
		apigatewayMethodIntegration := apigateway.Method_Integration{}

		if len(in.Spec.Integration.CacheKeyParameters) > 0 {
			apigatewayMethodIntegration.CacheKeyParameters = in.Spec.Integration.CacheKeyParameters
		}

		if !reflect.DeepEqual(in.Spec.Integration.RequestParameters, map[string]string{}) {
			apigatewayMethodIntegration.RequestParameters = in.Spec.Integration.RequestParameters
		}

		if in.Spec.Integration.Type != "" {
			apigatewayMethodIntegration.Type = in.Spec.Integration.Type
		}

		// TODO(christopherhein) move these to a defaulter
		apigatewayMethodIntegrationConnectionItem := in.Spec.Integration.Connection.DeepCopy()

		if apigatewayMethodIntegrationConnectionItem.ObjectRef.Kind == "" {
			apigatewayMethodIntegrationConnectionItem.ObjectRef.Kind = "Deployment"
		}

		if apigatewayMethodIntegrationConnectionItem.ObjectRef.APIVersion == "" {
			apigatewayMethodIntegrationConnectionItem.ObjectRef.APIVersion = "apigateway.awsctrl.io/v1alpha1"
		}

		if apigatewayMethodIntegrationConnectionItem.ObjectRef.Namespace == "" {
			apigatewayMethodIntegrationConnectionItem.ObjectRef.Namespace = in.Namespace
		}

		in.Spec.Integration.Connection = *apigatewayMethodIntegrationConnectionItem
		connectionId, err := in.Spec.Integration.Connection.String(client)
		if err != nil {
			return "", err
		}

		if connectionId != "" {
			apigatewayMethodIntegration.ConnectionId = connectionId
		}

		if !reflect.DeepEqual(in.Spec.Integration.RequestTemplates, map[string]string{}) {
			apigatewayMethodIntegration.RequestTemplates = in.Spec.Integration.RequestTemplates
		}

		if in.Spec.Integration.Uri != "" {
			apigatewayMethodIntegration.Uri = in.Spec.Integration.Uri
		}

		apigatewayMethodIntegrationIntegrationResponses := []apigateway.Method_IntegrationResponse{}

		for _, item := range in.Spec.Integration.IntegrationResponses {
			apigatewayMethodIntegrationIntegrationResponse := apigateway.Method_IntegrationResponse{}

			if item.ContentHandling != "" {
				apigatewayMethodIntegrationIntegrationResponse.ContentHandling = item.ContentHandling
			}

			if !reflect.DeepEqual(item.ResponseParameters, map[string]string{}) {
				apigatewayMethodIntegrationIntegrationResponse.ResponseParameters = item.ResponseParameters
			}

			if !reflect.DeepEqual(item.ResponseTemplates, map[string]string{}) {
				apigatewayMethodIntegrationIntegrationResponse.ResponseTemplates = item.ResponseTemplates
			}

			if item.SelectionPattern != "" {
				apigatewayMethodIntegrationIntegrationResponse.SelectionPattern = item.SelectionPattern
			}

			if item.StatusCode != "" {
				apigatewayMethodIntegrationIntegrationResponse.StatusCode = item.StatusCode
			}

		}

		if len(apigatewayMethodIntegrationIntegrationResponses) > 0 {
			apigatewayMethodIntegration.IntegrationResponses = apigatewayMethodIntegrationIntegrationResponses
		}
		if in.Spec.Integration.TimeoutInMillis != apigatewayMethodIntegration.TimeoutInMillis {
			apigatewayMethodIntegration.TimeoutInMillis = in.Spec.Integration.TimeoutInMillis
		}

		if in.Spec.Integration.ConnectionType != "" {
			apigatewayMethodIntegration.ConnectionType = in.Spec.Integration.ConnectionType
		}

		if in.Spec.Integration.PassthroughBehavior != "" {
			apigatewayMethodIntegration.PassthroughBehavior = in.Spec.Integration.PassthroughBehavior
		}

		if in.Spec.Integration.CacheNamespace != "" {
			apigatewayMethodIntegration.CacheNamespace = in.Spec.Integration.CacheNamespace
		}

		if in.Spec.Integration.ContentHandling != "" {
			apigatewayMethodIntegration.ContentHandling = in.Spec.Integration.ContentHandling
		}

		if in.Spec.Integration.Credentials != "" {
			apigatewayMethodIntegration.Credentials = in.Spec.Integration.Credentials
		}

		if in.Spec.Integration.IntegrationHttpMethod != "" {
			apigatewayMethodIntegration.IntegrationHttpMethod = in.Spec.Integration.IntegrationHttpMethod
		}

		apigatewayMethod.Integration = &apigatewayMethodIntegration
	}

	// TODO(christopherhein) move these to a defaulter
	apigatewayMethodRestApiItem := in.Spec.RestApi.DeepCopy()

	if apigatewayMethodRestApiItem.ObjectRef.Kind == "" {
		apigatewayMethodRestApiItem.ObjectRef.Kind = "Deployment"
	}

	if apigatewayMethodRestApiItem.ObjectRef.APIVersion == "" {
		apigatewayMethodRestApiItem.ObjectRef.APIVersion = "apigateway.awsctrl.io/v1alpha1"
	}

	if apigatewayMethodRestApiItem.ObjectRef.Namespace == "" {
		apigatewayMethodRestApiItem.ObjectRef.Namespace = in.Namespace
	}

	in.Spec.RestApi = *apigatewayMethodRestApiItem
	restApiId, err := in.Spec.RestApi.String(client)
	if err != nil {
		return "", err
	}

	if restApiId != "" {
		apigatewayMethod.RestApiId = restApiId
	}

	// TODO(christopherhein) move these to a defaulter
	apigatewayMethodAuthorizerItem := in.Spec.Authorizer.DeepCopy()

	if apigatewayMethodAuthorizerItem.ObjectRef.Kind == "" {
		apigatewayMethodAuthorizerItem.ObjectRef.Kind = "Deployment"
	}

	if apigatewayMethodAuthorizerItem.ObjectRef.APIVersion == "" {
		apigatewayMethodAuthorizerItem.ObjectRef.APIVersion = "apigateway.awsctrl.io/v1alpha1"
	}

	if apigatewayMethodAuthorizerItem.ObjectRef.Namespace == "" {
		apigatewayMethodAuthorizerItem.ObjectRef.Namespace = in.Namespace
	}

	in.Spec.Authorizer = *apigatewayMethodAuthorizerItem
	authorizerId, err := in.Spec.Authorizer.String(client)
	if err != nil {
		return "", err
	}

	if authorizerId != "" {
		apigatewayMethod.AuthorizerId = authorizerId
	}

	// TODO(christopherhein) move these to a defaulter
	apigatewayMethodResourceItem := in.Spec.Resource.DeepCopy()

	if apigatewayMethodResourceItem.ObjectRef.Kind == "" {
		apigatewayMethodResourceItem.ObjectRef.Kind = "Deployment"
	}

	if apigatewayMethodResourceItem.ObjectRef.APIVersion == "" {
		apigatewayMethodResourceItem.ObjectRef.APIVersion = "apigateway.awsctrl.io/v1alpha1"
	}

	if apigatewayMethodResourceItem.ObjectRef.Namespace == "" {
		apigatewayMethodResourceItem.ObjectRef.Namespace = in.Namespace
	}

	in.Spec.Resource = *apigatewayMethodResourceItem
	resourceId, err := in.Spec.Resource.String(client)
	if err != nil {
		return "", err
	}

	if resourceId != "" {
		apigatewayMethod.ResourceId = resourceId
	}

	if in.Spec.HttpMethod != "" {
		apigatewayMethod.HttpMethod = in.Spec.HttpMethod
	}

	apigatewayMethodMethodResponses := []apigateway.Method_MethodResponse{}

	for _, item := range in.Spec.MethodResponses {
		apigatewayMethodMethodResponse := apigateway.Method_MethodResponse{}

		if !reflect.DeepEqual(item.ResponseModels, map[string]string{}) {
			apigatewayMethodMethodResponse.ResponseModels = item.ResponseModels
		}

		if !reflect.DeepEqual(item.ResponseParameters, map[string]bool{}) {
			apigatewayMethodMethodResponse.ResponseParameters = item.ResponseParameters
		}

		if item.StatusCode != "" {
			apigatewayMethodMethodResponse.StatusCode = item.StatusCode
		}

	}

	if len(apigatewayMethodMethodResponses) > 0 {
		apigatewayMethod.MethodResponses = apigatewayMethodMethodResponses
	}
	if in.Spec.ApiKeyRequired || !in.Spec.ApiKeyRequired {
		apigatewayMethod.ApiKeyRequired = in.Spec.ApiKeyRequired
	}

	if !reflect.DeepEqual(in.Spec.RequestParameters, map[string]bool{}) {
		apigatewayMethod.RequestParameters = in.Spec.RequestParameters
	}

	template.Resources = map[string]cloudformation.Resource{
		"Method": apigatewayMethod,
	}

	// json, err := template.JSONWithOptions(&intrinsics.ProcessorOptions{NoEvaluateConditions: true})
	json, err := template.JSON()
	if err != nil {
		return "", err
	}

	return string(json), nil
}

// GetStackID will return stackID
func (in *Method) GetStackID() string {
	return in.Status.StackID
}

// GenerateStackName will generate a StackName
func (in *Method) GenerateStackName() string {
	return strings.Join([]string{"apigateway", "method", in.GetName(), in.GetNamespace()}, "-")
}

// GetStackName will return stackName
func (in *Method) GetStackName() string {
	return in.Spec.StackName
}

// GetTemplateVersionLabel will return the stack template version
func (in *Method) GetTemplateVersionLabel() (value string, ok bool) {
	value, ok = in.Labels[controllerutils.StackTemplateVersionLabel]
	return
}

// GetParameters will return CFN Parameters
func (in *Method) GetParameters() map[string]string {
	params := map[string]string{}
	cfnencoder.MarshalTypes(params, in.Spec, "Parameter")
	return params
}

// GetCloudFormationMeta will return CFN meta object
func (in *Method) GetCloudFormationMeta() metav1alpha1.CloudFormationMeta {
	return in.Spec.CloudFormationMeta
}

// GetStatus will return the CFN Status
func (in *Method) GetStatus() metav1alpha1.ConditionStatus {
	return in.Status.Status
}

// SetStackID will put a stackID
func (in *Method) SetStackID(input string) {
	in.Status.StackID = input
	return
}

// SetStackName will return stackName
func (in *Method) SetStackName(input string) {
	in.Spec.StackName = input
	return
}

// SetTemplateVersionLabel will set the template version label
func (in *Method) SetTemplateVersionLabel() {
	if len(in.Labels) == 0 {
		in.Labels = map[string]string{}
	}

	in.Labels[controllerutils.StackTemplateVersionLabel] = controllerutils.ComputeHash(in.Spec)
}

// TemplateVersionChanged will return bool if template has changed
func (in *Method) TemplateVersionChanged() bool {
	// Ignore bool since it will still record changed
	label, _ := in.GetTemplateVersionLabel()
	return label != controllerutils.ComputeHash(in.Spec)
}

// SetStatus will set status for object
func (in *Method) SetStatus(status *metav1alpha1.StatusMeta) {
	in.Status.StatusMeta = *status
}
